version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marvel-project
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
